/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

#ifndef __Elastos_DevSamples_Node_JSSimpleCalculator_R_H__
#define __Elastos_DevSamples_Node_JSSimpleCalculator_R_H__
#include <elatypes.h>
namespace Elastos {
namespace DevSamples {
namespace Node {
namespace JSSimpleCalculator {
class ECO_PUBLIC R {
    public: class attr {
    };
    public: class color {
        public: static const int button_border = 0x7f040000;
        public: static const int button_focused = 0x7f040002;
        public: static const int button_pressed = 0x7f040001;
        public: static const int button_text = 0x7f040006;
        public: static const int functional_button_normal = 0x7f040005;
        public: static const int number_button_normal = 0x7f040003;
        public: static const int operation_button_normal = 0x7f040004;
        public: static const int value = 0x7f040008;
        public: static const int value_background = 0x7f040007;
    };
    public: class dimen {
        public: static const int activity_horizontal_margin = 0x7f050000;
        public: static const int activity_vertical_margin = 0x7f050001;
        public: static const int button_separator_line_width = 0x7f050005;
        public: static const int number_button_text_size = 0x7f050002;
        public: static const int number_view_margin = 0x7f050003;
        public: static const int number_view_text_size = 0x7f050004;
    };
    public: class drawable {
        public: static const int functional_button_background_selector = 0x7f020000;
        public: static const int ic_launcher = 0x7f020001;
        public: static const int icon = 0x7f020002;
        public: static const int icon_change_precision = 0x7f020003;
        public: static const int number_button_background_selector = 0x7f020004;
        public: static const int operation_button_background_selector = 0x7f020005;
    };
    public: class id {
        public: static const int TableLayout1 = 0x7f090000;
        public: static const int button0 = 0x7f090017;
        public: static const int button1 = 0x7f090013;
        public: static const int button2 = 0x7f090014;
        public: static const int button3 = 0x7f090015;
        public: static const int button4 = 0x7f09000f;
        public: static const int button5 = 0x7f090010;
        public: static const int button6 = 0x7f090011;
        public: static const int button7 = 0x7f09000b;
        public: static const int button8 = 0x7f09000c;
        public: static const int button9 = 0x7f09000d;
        public: static const int buttonAssign = 0x7f090019;
        public: static const int buttonClear = 0x7f090006;
        public: static const int buttonDelete = 0x7f090005;
        public: static const int buttonDiv = 0x7f09000e;
        public: static const int buttonM = 0x7f090007;
        public: static const int buttonMinus = 0x7f090016;
        public: static const int buttonMminus = 0x7f090009;
        public: static const int buttonMplus = 0x7f090008;
        public: static const int buttonMul = 0x7f090012;
        public: static const int buttonPlus = 0x7f09001a;
        public: static const int buttonPlusMinus = 0x7f09000a;
        public: static const int buttonPoint = 0x7f090018;
        public: static const int buttonPow = 0x7f090003;
        public: static const int buttonSqrt = 0x7f090004;
        public: static const int horizontalScrollView = 0x7f090001;
        public: static const int menu_item_set_precision = 0x7f09001d;
        public: static const int seekBar = 0x7f09001c;
        public: static const int textView = 0x7f09001b;
        public: static const int textViewCurNum = 0x7f090002;
    };
    public: class layout {
        public: static const int layout_calc = 0x7f030000;
        public: static const int precision_dialog = 0x7f030001;
    };
    public: class menu {
        public: static const int calculator_menu = 0x7f080000;
    };
    public: class string {
        public: static const int app_name = 0x7f060000;
        /**  Global dialog items 
 Global dialog items 
         */
        public: static const int text_cancel_button = 0x7f060002;
        public: static const int text_infinity = 0x7f060008;
        public: static const int text_no_button = 0x7f060004;
        public: static const int text_ok_button = 0x7f060003;
        public: static const int text_rate_dialog = 0x7f060005;
        /**  Menu items 
 Menu items 
         */
        public: static const int text_set_precision_item = 0x7f060001;
        public: static const int text_too_long_value = 0x7f060007;
        /**  Calculator messages 
 Calculator messages 
         */
        public: static const int text_wrong_argument = 0x7f060006;
    };
    public: class style {
        /**  Base application theme. 
         */
        public: static const int AppTheme = 0x7f070000;
        public: static const int CalculatorButton = 0x7f070002;
        public: static const int CalculatorButton_Functional = 0x7f070004;
        public: static const int CalculatorButton_Number = 0x7f070003;
        public: static const int CalculatorButton_Operation = 0x7f070005;
        public: static const int CalculatorTableRow = 0x7f070001;
    };
};
};
};
};
};

#endif // __Elastos_DevSamples_Node_JSSimpleCalculator_R_H__
