/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

#ifndef __Elastos_DevSamples_Node_JSSimpleCalculator_R_H__
#define __Elastos_DevSamples_Node_JSSimpleCalculator_R_H__
#include <elatypes.h>
namespace Elastos {
namespace DevSamples {
namespace Node {
namespace JSSimpleCalculator {
class ECO_PUBLIC R {
    public: class attr {
    };
    public: class color {
        public: static const int button_border = 0x7f050000;
        public: static const int button_focused = 0x7f050002;
        public: static const int button_pressed = 0x7f050001;
        public: static const int button_text = 0x7f050006;
        public: static const int functional_button_normal = 0x7f050005;
        public: static const int number_button_normal = 0x7f050003;
        public: static const int operation_button_normal = 0x7f050004;
        public: static const int value = 0x7f050008;
        public: static const int value_background = 0x7f050007;
    };
    public: class dimen {
        public: static const int activity_horizontal_margin = 0x7f060000;
        public: static const int activity_vertical_margin = 0x7f060001;
        public: static const int button_separator_line_width = 0x7f060005;
        public: static const int number_button_text_size = 0x7f060002;
        public: static const int number_view_margin = 0x7f060003;
        public: static const int number_view_text_size = 0x7f060004;
    };
    public: class drawable {
        public: static const int functional_button_background_selector = 0x7f020000;
        public: static const int ic_launcher = 0x7f020001;
        public: static const int icon = 0x7f020002;
        public: static const int icon_change_precision = 0x7f020003;
        public: static const int number_button_background_selector = 0x7f020004;
        public: static const int operation_button_background_selector = 0x7f020005;
    };
    public: class id {
        public: static const int TableLayout1 = 0x7f0a0000;
        public: static const int button0 = 0x7f0a0017;
        public: static const int button1 = 0x7f0a0013;
        public: static const int button2 = 0x7f0a0014;
        public: static const int button3 = 0x7f0a0015;
        public: static const int button4 = 0x7f0a000f;
        public: static const int button5 = 0x7f0a0010;
        public: static const int button6 = 0x7f0a0011;
        public: static const int button7 = 0x7f0a000b;
        public: static const int button8 = 0x7f0a000c;
        public: static const int button9 = 0x7f0a000d;
        public: static const int buttonAssign = 0x7f0a0019;
        public: static const int buttonClear = 0x7f0a0006;
        public: static const int buttonDelete = 0x7f0a0005;
        public: static const int buttonDiv = 0x7f0a000e;
        public: static const int buttonM = 0x7f0a0007;
        public: static const int buttonMinus = 0x7f0a0016;
        public: static const int buttonMminus = 0x7f0a0009;
        public: static const int buttonMplus = 0x7f0a0008;
        public: static const int buttonMul = 0x7f0a0012;
        public: static const int buttonPlus = 0x7f0a001a;
        public: static const int buttonPlusMinus = 0x7f0a000a;
        public: static const int buttonPoint = 0x7f0a0018;
        public: static const int buttonPow = 0x7f0a0003;
        public: static const int buttonSqrt = 0x7f0a0004;
        public: static const int horizontalScrollView = 0x7f0a0001;
        public: static const int menu_item_set_precision = 0x7f0a001d;
        public: static const int seekBar = 0x7f0a001c;
        public: static const int textView = 0x7f0a001b;
        public: static const int textViewCurNum = 0x7f0a0002;
    };
    public: class layout {
        public: static const int layout_calc = 0x7f030000;
        public: static const int precision_dialog = 0x7f030001;
    };
    public: class menu {
        public: static const int calculator_menu = 0x7f090000;
    };
    public: class raw {
        public: static const int activity_calc = 0x7f040000;
        public: static const int c_demo_activity = 0x7f040001;
        public: static const int calculator = 0x7f040002;
        public: static const int custom_horizontal_scroll_view = 0x7f040003;
        public: static const int manifest = 0x7f040004;
        public: static const int r = 0x7f040005;
    };
    public: class string {
        public: static const int app_name = 0x7f070000;
        /**  Global dialog items 
 Global dialog items 
         */
        public: static const int text_cancel_button = 0x7f070002;
        public: static const int text_infinity = 0x7f070008;
        public: static const int text_no_button = 0x7f070004;
        public: static const int text_ok_button = 0x7f070003;
        public: static const int text_rate_dialog = 0x7f070005;
        /**  Menu items 
 Menu items 
         */
        public: static const int text_set_precision_item = 0x7f070001;
        public: static const int text_too_long_value = 0x7f070007;
        /**  Calculator messages 
 Calculator messages 
         */
        public: static const int text_wrong_argument = 0x7f070006;
    };
    public: class style {
        /**  Base application theme. 
         */
        public: static const int AppTheme = 0x7f080000;
        public: static const int CalculatorButton = 0x7f080002;
        public: static const int CalculatorButton_Functional = 0x7f080004;
        public: static const int CalculatorButton_Number = 0x7f080003;
        public: static const int CalculatorButton_Operation = 0x7f080005;
        public: static const int CalculatorTableRow = 0x7f080001;
    };
};
};
};
};
};

#endif // __Elastos_DevSamples_Node_JSSimpleCalculator_R_H__
